# Generated by Django 4.1.1 on 2022-09-10 05:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchinout', '0002_timmeinouut_remove_user_timestamp_user_userid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='timmeinouut',
            name='timestamp',
        ),
        migrations.AddField(
            model_name='timmeinouut',
            name='dateuser',
            field=models.DateField(null=True, verbose_name='Date'),
        ),
        migrations.AddField(
            model_name='timmeinouut',
            name='timestampin',
            field=models.TimeField(null=True, verbose_name='Timeofentry'),
        ),
        migrations.AddField(
            model_name='timmeinouut',
            name='timestampout',
            field=models.TimeField(null=True, verbose_name='Timeofout'),
        ),
    ]
