# Generated by Django 4.1.1 on 2022-09-10 05:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchinout', '0003_remove_timmeinouut_timestamp_timmeinouut_dateuser_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='timein',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True, verbose_name='Userid')),
                ('dateuser', models.DateField(null=True, verbose_name='Date')),
                ('timestampin', models.TimeField(null=True, verbose_name='Timeofentry')),
            ],
        ),
        migrations.CreateModel(
            name='timeout',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('userid', models.CharField(max_length=50, null=True, verbose_name='Userid')),
                ('dateuser', models.DateField(null=True, verbose_name='Date')),
                ('timestampout', models.TimeField(null=True, verbose_name='Timeofout')),
            ],
        ),
        migrations.DeleteModel(
            name='timmeinouut',
        ),
    ]
