# Generated by Django 4.1.1 on 2022-09-10 13:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('punchinout', '0004_timein_timeout_delete_timmeinouut'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timein',
            name='dateuser',
            field=models.DateField(auto_now_add=True, null=True, verbose_name='Date'),
        ),
    ]
